# Generated by Django 4.1.3 on 2024-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='account_img/')),
                ('waiterid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
                ('tableno', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('groups', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email address already exists.'}, max_length=320, null=True, unique=True)),
                ('phone', models.IntegerField(default=0, help_text='Contact phone number')),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('total_received', models.FloatField(blank=True, default=0, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
