# Generated by Django 4.1.3 on 2024-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
    ]
