# Generated by Django 4.1.3 on 2024-09-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_is_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='waiterid',
            new_name='userid',
        ),
    ]
