# Generated by Django 4.2.16 on 2024-09-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ordernum',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tableno',
        ),
    ]
