# Generated by Django 4.1.3 on 2024-09-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_account_ordernum_remove_account_tableno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_sales',
            new_name='is_client',
        ),
    ]
