# Generated by Django 4.1.3 on 2024-09-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_task'),
        ('Account', '0006_rename_is_sales_account_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='assigned_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.task'),
        ),
    ]
