# Generated by Django 4.1.3 on 2024-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_account_assigned_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='task_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
