# Generated by Django 4.1.3 on 2024-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_account_task_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending_withdraw_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
