# Generated by Django 4.1.3 on 2024-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_account_pending_withdraw_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_withdrawed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
