# Generated by Django 4.1.3 on 2024-09-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_account_total_withdrawed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_received',
        ),
    ]
