# Generated by Django 4.1.3 on 2024-09-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_remove_account_total_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='task_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
