# Generated by Django 4.1.3 on 2024-09-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_account_task_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='encounter_negative',
            field=models.BooleanField(default=False),
        ),
    ]
