# Generated by Django 4.2.16 on 2024-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_account_encounter_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='vip_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sets_per_day', models.IntegerField(blank=True, null=True)),
                ('profit_per_submission', models.FloatField(blank=True, null=True)),
                ('account_minimum_balance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
