# Generated by Django 4.2.16 on 2024-10-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_vip_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vip_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Account.vip_plans'),
        ),
    ]
