# Generated by Django 4.2.16 on 2025-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_account_vip_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_premium_products',
            field=models.BooleanField(default=True),
        ),
    ]
